let numberOne = 10;
let numberTwo = 20;
console.log(numberOne + numberTwo); // ?
console.log(numberOne - numberTwo); // ?
console.log(numberOne * numberTwo); // ?
console.log(numberOne / numberTwo); // ?
console.log(numberOne % numberTwo); // ?
console.log(numberOne ** numberTwo); // ?
console.log(numberOne++); // ?
console.log(++numberOne); // ?
console.log(numberOne--); // ?
console.log(--numberOne); // ?
console.log(--numberOne + numberTwo++); // ?
console.log(numberOne-- - --numberTwo + numberTwo++); // ?
console.log(numberOne++ / numberTwo++); // ?
console.log(numberOne++ * --numberTwo); // ?

var rezultatas = 5 + 3;
console.log(rezultatas); // Rezultatas: 8

var rezultatas = 10 - 4;
console.log(rezultatas); // Rezultatas: 6

var rezultatas = 6 * 7;
console.log(rezultatas); // Rezultatas: 42

var rezultatas = 20 / 4;
console.log(rezultatas); // Rezultatas: 5

var rezultatas = 17 % 4;
console.log(rezultatas); // Rezultatas: 1

var rezultatas = 2 ** 3;
console.log(rezultatas); // Rezultatas: 8
