let funnyNumber = 12345; 
console.log(String(funnyNumber), typeof String(funnyNumber));
let funnyString = '12345'; 
console.log(Number(funnyString), typeof Number(funnyString));
let funnyTrue = '1'; 
console.log(Boolean(funnyTrue), typeof Boolean(funnyTrue));
let funnyFalse = '0'; 
console.log(Boolean(funnyFalse), typeof Boolean(funnyFalse));
let isTrue = false; 
console.log(String(isTrue), typeof String(isTrue));
let isFalse = true; 
console.log(Number(isFalse), typeof Number(isFalse));
let funnyText = 'JavaScript is dynamic programming language.'; 
console.log(Number(funnyText), typeof Number(funnyText));
let funnyNull = null; 
console.log(String(funnyNull), typeof String(funnyNull));
let funnyUndefined = undefined; 
console.log(String(funnyUndefined), typeof String(funnyUndefined));
let isTrue = true; 
console.log(String(isTrue), typeof String(isTrue));
let isFalse = false; 
console.log(String(isFalse), typeof String(isFalse));
let booleanString = 'true'; 
console.log(Number(booleanString), typeof Number(booleanString));
let otherBooleanString = 'false'; 
console.log(Boolean(otherBooleanString), typeof Boolean(otherBooleanString));