const numberVariable = 42;
console.log(typeof numberVariable);

const bigintVariable = 1234567890123456789012345678901234567890n;
console.log(typeof bigintVariable);

const stringVariable = "Hello, world!";
console.log(typeof stringVariable);

const booleanVariable = true;
console.log(typeof booleanVariable);

let undefinedVariable;
console.log(typeof undefinedVariable);

const nullVariable = null;
console.log(typeof nullVariable);

const objectVariable = { key: "value" };
console.log(typeof objectVariable);
